spring:
  datasource:
    url: jdbc:mysql://localhost:3306/layman_starter?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tokyo
    username: root
    password: 12345678


mybatis-plus:
  mapper-locations:
    - classpath*:/com/**/mapper/*.xml


log:
  path: _app_logs