spring:
  profiles:
    active: @profileName@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


mybatis-plus:
  mapper-locations:
    - classpath*:/com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: layman-starter-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer'  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /ums/admin/login
      - /ums/admin/register
      - /ums/admin/info
      - /ums/admin/logout
