spring:
  datasource:
    url: jdbc:mysql://localhost:3306/layman_starter?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Tokyo
    username: root
    password: 12345678

log:
  path: _app_logs

redis:
  database: layman
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时