spring:
  profiles:
    active: @profileName@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


mybatis-plus:
  mapper-locations:
    - classpath*:/com/**/mapper/*.xml


